[package]
name = "tern"
version = "0.1.1"
edition = "2024"

[dependencies]
postgres = "0.19.10"
clap = { version = "4.3.5", features = ["derive"] }
chrono = "0.4.40"
toml = "0.8.20"
log = "0.4.27"
env_logger = "0.11.8"
colored = "3.0.0"
